Adding Header and Navigation
bizznest-dev/collaboration-repository pull request #16
Opened 2023-12-12 20:07 UTC by elimanzo

Added header+navigation+css stylles
Closes #3 
Web:
![webHeader](https://i.gyazo.com/bf45892e52c6c66856cfd00531b67986.png)

Mobile:
![mobileHeader](https://i.gyazo.com/edc20329818faa8eb5ff1de985e4a658.png)

2023-12-12 23:55 UTC, alexrdrgz requested changes
Awesome edits this is looking real good, I left an example of how to structure a navigation. Other than that everythings looking good, i like that your using css embedded targetting as well :)

2023-12-12 23:55 UTC, alexrdrgz commented on index.html
> +            <li><a href="#projects">Projects</a></li>
So the best practice for a navigation would be the following structure

```
<nav>
  <ul>
    <li><a></a></li>
    <li><a></a></li>
  </ul>
</nav>
```

2023-12-12 23:55 UTC, alexrdrgz commented on index.html
> +            <li><a href="#projects">Projects</a></li>
you could add another container in it if needing for spacing or flex box or something like that but the general structure is best like this, especially for screen readers

2023-12-15 00:29 UTC, joavelar commented
This is looks good to me.

2023-12-20 23:07 UTC, alexrdrgz approved these changes
Looks good! Nice refactor on the nav

2023-12-21 18:54 UTC, merged